spring:
    profiles:
        active: local
jwt:
    secret: 16xCExK5oRjE4+eyW7Q+SLNs0sVAq9uUGykyEp/FULA=
openai:
    #在这里重新申请 https://platform.openai.com/account/api-keys
    apikey: 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
    gpt3_5url: https://api.openai.com/v1/chat/completions